#!/usr/bin/env bash
# Script to transfer files from client to server

if [ "$#" -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assign arguments to variables
FILE="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE" "$USERNAME@$SERVER_IP":~

# Check if scp was successfull
if [ $? -eq 0 ]; then
	echo "File transferred successfully to $USERNAME@$SERVER_IP:~/$FILE"
else
	echo "Error: File transfer failed"
fi
