#!/usr/bin/env bash
# Script to install and configure Nginx web server

sudo apt-get update -y
sudo apt-get install nginx -y

sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

echo "Hello World!" > /var/www/html/index.html

sudo service nginx restart
