#!/usr/bin/env bash
# Script to configure Nginx redirection

apt-get update -y
apt-get install nginx -y

echo "server {
	listen 80;
	server_name _;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	location / {
		try_files \$uri \$uri/ =404;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
