#!/usr/bin/env bash
# Script to configure Nginx custom 404 page

apt-get update -y
apt-get install nginx -y

echo "server {
	listen 80;
	server_name _;

	error_page 404 /custom_404.html;
	location = /custom_404.html {
		root /var/www/html;
		internal;
	}

	location / {
		try_files \$uri \$uri/ =404
	}
}" > /etc/nginx/sites-available/default

service nginx restart
